#!/usr/bin/perl

use v5.14;
use warnings;
use English;
use Munin::Plugin;

#%# family=auto
#%# capabilities=autoconf

my $nxcommand = "/var/www/nextcloud/occ";
my $nxuser    = "www-data";



if ( $ARGV[0] and $ARGV[0] eq "autoconf" ) {
    if ( -x $nxcommand ) {
        print "yes\n";
        exit 0;
    } else {
        print "no\n";
        exit 1;
    }
}

if ( $ARGV[0] and $ARGV[0] eq "config" ) {
    print <<'EOF';
graph_title NextCloud Users Usage Report
graph_info Users without quota show at 50%
graph_args --base 100 -l 0
graph_vlabel Percent Used
graph_category nextcloud
EOF

    if ( -x $nxcommand ) {
        my @cmdout = qx($nxcommand user:list)
          or die "Failed to execute \"$nxcommand\"";
        foreach my $line (@cmdout) {
            my ($user) = ( $line =~ m(^\s+\-\s(\w+)\:) );
            print "$user.label $user\n";
			#print "$user.info Absolute Data consumed\n"
        }

    }
    exit 0;
}

if ( -x $nxcommand ) {
    my @cmdout = qx($nxcommand  usage-report:generate)
      or die "Failed to execute \"$nxcommand\"";
		
        foreach my $line (@cmdout) {
            my ($user, $quota, $usage) = ( $line =~ m(^"(\w+)","[^d+]+.*",(\-?\d+),(\d+)) );
			my $percent;
			if ( $quota < -1) {
				$percent = 50;
			 } else {
				 $percent = int ( $usage / ( $quota / 100 ));
			}
		
		
		$usage = scaleNumber($usage, 'B', 0);
		print "$user.value $percent\n";
		#print "$user.info $usage\n";
        }
}

